### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by MrProditio** [haste/tales-beyond#17]
Is it possible that it does not work in dark mode? The background and text are a very similar light color to me. This happens in attributes, skills, initiative, spell hit bonus and in the description of characteristics and traits, but not in saves or spell damage/effect.
![image](https://github.com/haste/tales-beyond/assets/107200647/0227b6c9-0ccc-4023-8648-4deeca1906c5)

**Comment by haste** [comment]
Looks like there indeed are some issues with underdark mode now.  I'll see if I can get a quick fix for it out shortly.

**Comment by haste** [comment]
I've pushed 0.13.1 which should improve it for now. It might take a bit before it's approved. For Firefox it usually takes 5-15 minutes, while Chrome can be up to an hour.
