### ISSUE TITLE
Differentiated uses for alt/cltr/shift

### ISSUE THREAD

**Issue by MrProditio** [haste/tales-beyond#18]
It would be a good idea, and very useful, to separate the functions of the shift, control and alt keys, for example: 
- Pressing Shift could make the roll with advantage (Rolled Eldritch Blast (ADV).
- Pressing Control could be done with disadvantage (Rolled Eldritch Blast (DIS).
- Pressing Alt could roll basic critical damage, doubling the die to roll, but adding only once the bonus (Rolled Eldritch Blast (CRIT).
This would be enhanced if the text could be modified in some way, for example, by darkening the result that will not be taken into account (the lowest or highest, depending on whether the roll is made with advantage or disadvantage), thus highlighting the white text more as the result to be taken, or making only the result that corresponds be shown on the screen.

![Sample](https://github.com/haste/tales-beyond/assets/107200647/b916592f-9f2f-4af3-833b-ed4e1634d7a4)
* This image is a simple photoshop retouching.

**Comment by haste** [comment]
Yes, adding options to let people control these a bit more is something I want to do.

TaleSpire doesn't really let us do much more than sending label and dice to it, so we currently can't tell it to highlight the lower/higher.

**Comment by haste** [comment]
I've pushed an update where you can behavior a bit for the modifier keys. It just let's you change the text within the paranthesis to `ADV`, `DIS` and `ADV/DIS`, but it makes your intention a bit clearer to other players at least.

TaleSpire has also said they're looking into a new more powerful dice syntax, so the other items might be possible in the future. :smile:
